version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g yarn
  pre_build:
    commands:
      - yarn install --silent
  build:
    commands:
      - mkdir -p target/stg
      - mkdir target/prod
      - npx serverless package --package target/stg --stage stg
      - npx serverless package --package target/prod --stage prod
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
    - package.json
