version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless serverless-bundle
  pre_build:
    commands:
      - npm install --silent --no-progress
  build:
    commands:
      - mkdir -p target/stg
      - mkdir target/prod
      - cd server
      - cp deploy.sh ..
      - cp serverless.yml ..
      - serverless package --package ../target/stg --stage stg
      - serverless package --package ../target/prod --stage prod
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
