version: "3"
services:
  mazer-server:
    build: .
    links:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - RUNTIME="DOCKER"
    healthcheck:
      test: curl 127.0.0.1:4000/maze/
      interval: 60s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo
    volumes:
      - "/db/data:/data/db"
#    healthcheck:
#      test: echo 'db.stats().ok'
#      interval: 5s
#      timeout: 5s
#      retries: 12
