version: "3"
services:
  mazer-server:
    build: .
    links:
      - mongo
    ports:
      - ${PORT}:${PORT}
    environment:
      - RUNTIME=$RUNTIME
      - PORT=${PORT}
    healthcheck:
      test: curl 127.0.0.1:$PORT/maze/
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      - "/db/data:/data/db"
    healthcheck:
      test: echo 'db.stats().ok'
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped
