version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g yarn
      - mv deploy.package.json package.json
  pre_build:
    commands:
      - yarn install --silent
  build:
    commands:
      - npx serverless deploy --stage $env --package $CODEBUILD_SRC_DIR/target/$env
